[project]
name = "nouga"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.8",
    "google-api-python-client>=2.161.0",
    "pandas>=2.2.3",
    "python-dotenv>=1.0.1",
]
